# Changes here will be overwritten by Copier
_commit: 9b1969e
_src_path: git@github.com:pupil-labs/pl-template.git
author_email: info@pupil-labs.com
author_fullname: Pupil Labs GmbH
author_username: pupil-labs
copyright_license: Proprietary
debug_module: false
project_description: IR Plane Tracker
project_name: IR Plane Tracker
publish_to_pypi: false
python_package_distribution_name: pupil-labs-ir-plane-tracker
python_package_import_name: ir_plane_tracker
repository_name: pl-ir-plane-tracker
repository_namespace: pupil-labs
repository_provider: github.com
